CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.applicationtable (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tablename varchar(150) NOT NULL UNIQUE,
    displayname varchar(250) NULL,
    enableaudit boolean NOT NULL DEFAULT false,
    isactive boolean NOT NULL DEFAULT true,
    createdon timestamptz NOT NULL DEFAULT NOW(),
    createdby varchar(100) NULL,
    modifiedon timestamptz NULL,
    modifiedby varchar(100) NULL
);

CREATE TABLE IF NOT EXISTS public.fieldmapper (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entityname varchar(150) NOT NULL,
    fieldname varchar(150) NOT NULL,
    columnname varchar(150) NOT NULL,
    datatype varchar(100) NOT NULL,
    displayname varchar(250) NULL,
    properties text NULL,
    defaultvalue text NULL,
    allowupdate boolean NOT NULL DEFAULT true,
    isactive boolean NOT NULL DEFAULT true,
    createdon timestamptz NOT NULL DEFAULT NOW(),
    createdby varchar(100) NULL,
    modifiedon timestamptz NULL,
    modifiedby varchar(100) NULL
);

CREATE INDEX IF NOT EXISTS ix_fieldmapper_entityname_active
    ON public.fieldmapper (entityname, isactive);

CREATE TABLE IF NOT EXISTS public.auditlog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transactiontable varchar(150) NOT NULL,
    transactionid uuid NOT NULL,
    modifiedby varchar(150) NULL,
    operation varchar(30) NOT NULL,
    changelog jsonb NOT NULL,
    createdon timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_auditlog_table_transaction
    ON public.auditlog (transactiontable, transactionid);

CREATE TABLE IF NOT EXISTS public.fetchquerydefinition (
    querynumber bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(500) NOT NULL,
    querytext text NULL,
    fetchjson jsonb NULL,
    isfetchjson boolean NOT NULL DEFAULT false,
    parameterdefinition jsonb NULL,
    isactive boolean NOT NULL DEFAULT true,
    createdby varchar(100) NULL,
    createdon timestamptz NOT NULL DEFAULT NOW(),
    modifiedby varchar(100) NULL,
    modifiedon timestamptz NULL,
    versionno integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS public.fetchquerytablemap (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    querynumber bigint NOT NULL REFERENCES public.fetchquerydefinition(querynumber),
    tablename varchar(150) NOT NULL,
    createdon timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_fetchquerytablemap_querynumber
    ON public.fetchquerytablemap (querynumber);

CREATE INDEX IF NOT EXISTS ix_fetchquerytablemap_tablename
    ON public.fetchquerytablemap (tablename);

CREATE TABLE IF NOT EXISTS public.fetchqueryauditlog (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    querynumber bigint NOT NULL REFERENCES public.fetchquerydefinition(querynumber),
    actionname varchar(50) NOT NULL,
    executedquery text NULL,
    parametersjson jsonb NULL,
    resultcount integer NULL,
    status varchar(30) NOT NULL,
    errormessage text NULL,
    createdby varchar(100) NULL,
    createdon timestamptz NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_fetchqueryauditlog_querynumber
    ON public.fetchqueryauditlog (querynumber, createdon DESC);
