<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JanaticsApi.Application\JanaticsApi.Application.csproj" />
    <ProjectReference Include="..\JanaticsApi.Infrastructure\JanaticsApi.Infrastructure.csproj" />
    <ProjectReference Include="..\JanaticsApi.Shared\JanaticsApi.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.*" />
    <PackageReference Include="Asp.Versioning" Version="10.*" />
    <PackageReference Include="Asp.Versioning.ApiExplorer" Version="10.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.*" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Instrumentation.StackExchangeRedis" Version="1.*" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.*" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="7.*" />
    <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.*" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="7.*" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" Version="7.*" />
    <PackageReference Include="HealthChecks.UI.Client" Version="7.*" />
  </ItemGroup>

</Project>
